OC-4529 Remove the "Verify your Identity" banner on ecommerce receipt page
open-craft/ecommerce pull request #10
Opened 2018-08-31 17:01 UTC by lgp171188

Remove the "Verify your Identity" banner on ecommerce receipt page and replace it with a button to go to the LMS dashboard.

**Screenshot**
![receipt_page](https://user-images.githubusercontent.com/218870/44925837-25156600-ad6d-11e8-9c71-cff2b16d0ec4.png)

**Testing instructions**
- Revert the changes in PR #3.
- Create a course on LMS.
- Add the course on the ecommerce portal under one of the paid options.
- Generate a '100% off' enrollment coupon for the course.
- Enroll a student using the enrollment coupon created in the previous step.
- Check that the 'Verify your Identity' banner does not show up and instead there is a button to navigate to the LMS dashboard.

**Reviewers**
- [ ] @kaizoku

2018-09-05 02:50 UTC, kaizoku requested changes

2018-09-05 02:50 UTC, kaizoku commented on ecommerce/templates/edx/checkout/receipt.html
>        {% if verification_url and not user_verified %}
Would it be better to just remove this if/else clause altogether?

The text and styling for the button added here is slightly different from the one below, if we didn't duplicate them we wouldn't have to try to match them.

2018-09-06 14:41 UTC, lgp171188 commented on ecommerce/templates/edx/checkout/receipt.html
>        {% if verification_url and not user_verified %}
@kaizoku, that was so obvious and I am embarrassed to have missed it. Will fix it and update the PR now.

2018-09-06 15:01 UTC, lgp171188 commented
@kaizoku, I have updated the PR to address your review comment.

2018-09-07 00:02 UTC, kaizoku commented
Thanks for the update @lgp171188 
:+1:

- [✓] I tested this: (deployed in devstack, checked that verification banner doesn't show)
- [✓] I read through the code
- [✓] I checked for accessibility issues
- [n/a] Includes documentation

2018-09-07 00:02 UTC, kaizoku approved these changes

2018-09-07 00:02 UTC, kaizoku commented
Thanks for the update @lgp171188 
:+1:

- [✓] I tested this: (deployed in devstack, checked that verification banner doesn't show)
- [✓] I read through the code
- [✓] I checked for accessibility issues
- [n/a] Includes documentation

2018-09-09 16:20 UTC, lgp171188 commented
@kaizoku, I am merging this PR now.

2018-09-09 16:20 UTC, merged